name: auto build

on: 
  push:
    branches: [ main ]
    paths:
    - 'source/**'
    - 'dub.json'
    - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'source/**'
    - 'dub.json'
    - '.github/workflows/**'

jobs:
  build:
    name: Dub Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup dlang
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}
        
      - name: build
        run: dub build --build=release
