name: 自动编译

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

# 触发条件：推送到 main 分支、或向 main 提交 PR 时触发
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest # 使用 Windows 最新版运行环境
    steps:
      # 1. 检出仓库代码
      - name: 检出代码
        uses: actions/checkout@v5
      
      # 2. 安装 D 编译器 + dub（稳定版 dmd）
      - name: 安装 D 环境
        uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
        with:
          compiler: dmd-stable # 也可填 ldc-stable 使用 LDC 编译器

     
